name: Build and Push FastAPI Docker Image to ECR

on:
  push:
    branches:
      - main
    paths:
      - 'api/**'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    uses: ./.github/workflows/build_and_push_to_ecr.yaml
    with:
      image_name: fastapi-app
      image_path: api