# use build_and_push_to_ecr.yaml to build and push the Docker image to Amazon ECR.

name: Build and Push Lambda docker Image to ECR

on:
  push:
    branches:
      - crawl
    paths:
      - 'lambda/**'
  workflow_dispatch:

jobs:
  build-and-push:
    uses: ./.github/workflows/build_and_push_to_ecr.yaml
    with:
      image_name: fastapi-lambda
      image_path: lambda