name: Deploy Lambda

on:
  push:
    branches:
      - crawl
  workflow_call:
    inputs:
      lambda_name:
        description: 'Name of the Lambda'
        required: true
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      AWS_ACCOUNT_ID: 938674861148
      AWS_REGION: us-east-1

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/gha-iam-role
        aws-region: ${{ env.AWS_REGION }}

    - name: Update Lambda function
      uses: aws-actions/aws-lambda-deploy@v1
      with:
        function-name: fastapi-lambda
        image-uri: ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/fastapi-lambda:latest