name: Deploy ECS Service

on:
  workflow_call:
    inputs:
      service_name:
        description: 'Name of the ECS service'
        required: true
        type: string
      cluster_name:
        description: 'Name of the ECS cluster'
        required: true
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      AWS_ACCOUNT_ID: 938674861148
      AWS_REGION: us-east-1

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/gha-ecs-lambda-iam-role
        aws-region: ${{ env.AWS_REGION }}

    - name: Restart ECS Service
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        service: fastapi
        cluster: fastapi-cluster
        wait-for-service-stability: true